apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myaks-9466"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myaks-9466"
  template:
    metadata:
      labels:
        app: "myaks-9466"
    spec:
      containers:
        - name: "myaks-9466"
          image: "kevinji80.azurecr.io/myaks"
          ports:
          - containerPort: 80