on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: kevinji80.azurecr.io
        username: ${{ secrets.acr_kevinji80_username }}
        password: ${{ secrets.acr_kevinji80_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/app" -f  "app/Dockerfile" -t kevinji80.azurecr.io/myaks:${{ github.sha }} --label dockerfile-path=app/Dockerfile
        docker push kevinji80.azurecr.io/myaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myaksa7bd | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myaksa7bd`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myaksa7bd
        container-registry-url: kevinji80.azurecr.io
        container-registry-username: ${{ secrets.acr_kevinji80_username }}
        container-registry-password: ${{ secrets.acr_kevinji80_password }}
        secret-name: myaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myaksa7bd
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          kevinji80.azurecr.io/myaks:${{ github.sha }}
        imagepullsecrets: |
          myaksdockerauth
